//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AudF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Data.DataSet GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        client.ServiceReference1.CompositeType GetDataUsingDataContract(client.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<client.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(client.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dob_red_aud", ReplyAction="http://tempuri.org/IService1/dob_red_audResponse")]
        void dob_red_aud(int flag, string korp, string Nn, string po, string pl, string v_a, string vm, string spec, string nal_pr, string vis, string sh, string dl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dob_red_aud", ReplyAction="http://tempuri.org/IService1/dob_red_audResponse")]
        System.Threading.Tasks.Task dob_red_audAsync(int flag, string korp, string Nn, string po, string pl, string v_a, string vm, string spec, string nal_pr, string vis, string sh, string dl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dob_red_ob", ReplyAction="http://tempuri.org/IService1/dob_red_obResponse")]
        void dob_red_ob(int flag, string kor, string Nn, string n_ob, string cost, string invent_n, string d_u, string d_s, string ot_lic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dob_red_ob", ReplyAction="http://tempuri.org/IService1/dob_red_obResponse")]
        System.Threading.Tasks.Task dob_red_obAsync(int flag, string kor, string Nn, string n_ob, string cost, string invent_n, string d_u, string d_s, string ot_lic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dob_red_rem", ReplyAction="http://tempuri.org/IService1/dob_red_remResponse")]
        void dob_red_rem(int flag, string kor, string Nn, string n_sm, string vid_rem, string p_o, string cost, string d_n, string d_okon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dob_red_rem", ReplyAction="http://tempuri.org/IService1/dob_red_remResponse")]
        System.Threading.Tasks.Task dob_red_remAsync(int flag, string kor, string Nn, string n_sm, string vid_rem, string p_o, string cost, string d_n, string d_okon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<client.ServiceReference1.IService1>, client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public client.ServiceReference1.CompositeType GetDataUsingDataContract(client.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(client.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void dob_red_aud(int flag, string korp, string Nn, string po, string pl, string v_a, string vm, string spec, string nal_pr, string vis, string sh, string dl) {
            base.Channel.dob_red_aud(flag, korp, Nn, po, pl, v_a, vm, spec, nal_pr, vis, sh, dl);
        }
        
        public System.Threading.Tasks.Task dob_red_audAsync(int flag, string korp, string Nn, string po, string pl, string v_a, string vm, string spec, string nal_pr, string vis, string sh, string dl) {
            return base.Channel.dob_red_audAsync(flag, korp, Nn, po, pl, v_a, vm, spec, nal_pr, vis, sh, dl);
        }
        
        public void dob_red_ob(int flag, string kor, string Nn, string n_ob, string cost, string invent_n, string d_u, string d_s, string ot_lic) {
            base.Channel.dob_red_ob(flag, kor, Nn, n_ob, cost, invent_n, d_u, d_s, ot_lic);
        }
        
        public System.Threading.Tasks.Task dob_red_obAsync(int flag, string kor, string Nn, string n_ob, string cost, string invent_n, string d_u, string d_s, string ot_lic) {
            return base.Channel.dob_red_obAsync(flag, kor, Nn, n_ob, cost, invent_n, d_u, d_s, ot_lic);
        }
        
        public void dob_red_rem(int flag, string kor, string Nn, string n_sm, string vid_rem, string p_o, string cost, string d_n, string d_okon) {
            base.Channel.dob_red_rem(flag, kor, Nn, n_sm, vid_rem, p_o, cost, d_n, d_okon);
        }
        
        public System.Threading.Tasks.Task dob_red_remAsync(int flag, string kor, string Nn, string n_sm, string vid_rem, string p_o, string cost, string d_n, string d_okon) {
            return base.Channel.dob_red_remAsync(flag, kor, Nn, n_sm, vid_rem, p_o, cost, d_n, d_okon);
        }
    }
}
